stages:
  - deploy

deploy:
  stage: deploy

  tags:
    - docker

  script:
    - docker build -t my-first-app:v1 .
    - docker stop flask-container || true
    - docker rm flask-container || true
    - docker run -d --name flask-container -p 5003:5000 my-first-app:v1

  only:
    - main
